"""
Point-group rotation matrices for the tetrahedral, octahedral and icosahedral
groups, generated by closure from exact generators.

Each group is the closure of two or three generator rotations under matrix
multiplication, computed in float64 (`_close_group`). The generators are
written in closed form -- integer matrices, a cyclic permutation, or a
Rodrigues rotation about an axis given in terms of the golden ratio -- so
every element is a true rotation to float64 rounding, and the set is closed
under composition to the same precision.

The settings match RELION's: ``T`` has its 3-fold axis on +z, ``O`` has its
4-fold axes on x, y and z, and ``I1``/``I2`` are the two 222 settings (2-fold
axes on x, y and z) that differ in which of the two yz-plane 5-fold axes lies
closer to z. ``I`` is an alias of ``I2``.
"""

from __future__ import annotations

import math

import torch

#: Golden ratio. The icosahedron's 5-fold axes in a 222 setting are the cyclic
#: permutations of ``(0, ±1, ±PHI)`` (or of ``(0, ±PHI, ±1)``, the other setting).
PHI = (1 + math.sqrt(5)) / 2

#: Two elements closer than this are the same group element. The closure runs
#: in float64, so genuine duplicates agree to ~1e-15 and distinct elements of
#: these groups differ by at least ~0.3.
_SAME_ELEMENT_ATOL = 1e-9


def _rotation_about(axis: tuple[float, float, float], angle_deg: float) -> torch.Tensor:
    """Rodrigues rotation by ``angle_deg`` about ``axis`` (normalised here), float64."""
    u = torch.tensor(axis, dtype=torch.float64)
    u = u / u.norm()
    K = torch.tensor(
        [[0.0, -u[2], u[1]], [u[2], 0.0, -u[0]], [-u[1], u[0], 0.0]],
        dtype=torch.float64,
    )
    theta = math.radians(angle_deg)
    return (
        torch.eye(3, dtype=torch.float64)
        + math.sin(theta) * K
        + (1 - math.cos(theta)) * (K @ K)
    )


def _close_group(generators: list[torch.Tensor], order: int) -> torch.Tensor:
    """
    Close a set of rotation matrices under multiplication.

    Parameters
    ----------
    generators : list of torch.Tensor
        Float64 (3, 3) rotation matrices.
    order : int
        The expected group order. Closure stops with an error past it, which
        catches a generator that is not an element of the intended group
        (the closure of such a set is either a larger group or infinite).

    Returns
    -------
    torch.Tensor
        Shape (order, 3, 3), float32, identity first.
    """
    elements = [torch.eye(3, dtype=torch.float64)]
    frontier = list(elements)
    while frontier:
        new = []
        for g in frontier:
            for h in generators:
                p = g @ h
                if all(
                    not torch.allclose(p, e, atol=_SAME_ELEMENT_ATOL, rtol=0.0)
                    for e in elements
                ):
                    elements.append(p)
                    new.append(p)
                    if len(elements) > order:
                        raise RuntimeError(
                            f"Closure exceeded the expected group order {order}; "
                            "the generators are not all elements of one group."
                        )
        frontier = new
    if len(elements) != order:
        raise RuntimeError(
            f"Closure produced {len(elements)} elements, expected {order}."
        )
    return torch.stack(elements).to(torch.float32)


def _tetrahedral_matrices() -> torch.Tensor:
    """T (12 elements): 3-fold axis on +z, one 2-fold axis at ``(0, sqrt(2/3), sqrt(1/3))``."""
    return _close_group(
        [
            _rotation_about((0.0, 0.0, 1.0), 120.0),
            _rotation_about((0.0, math.sqrt(2 / 3), math.sqrt(1 / 3)), 180.0),
        ],
        order=12,
    )


def _octahedral_matrices() -> torch.Tensor:
    """O (24 elements): 4-fold axes on x, y and z."""
    rz90 = torch.tensor(
        [[0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0]], dtype=torch.float64
    )
    rx90 = torch.tensor(
        [[1.0, 0.0, 0.0], [0.0, 0.0, -1.0], [0.0, 1.0, 0.0]], dtype=torch.float64
    )
    return _close_group([rz90, rx90], order=24)


def _icosahedral_222(five_fold_axis: tuple[float, float, float]) -> torch.Tensor:
    """I (60 elements) in a 222 setting: 2-fold axes on x, y, z; a 5-fold axis as given."""
    two_fold_z = torch.diag(torch.tensor([-1.0, -1.0, 1.0], dtype=torch.float64))
    three_fold_111 = torch.tensor(
        [[0.0, 0.0, 1.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]], dtype=torch.float64
    )
    return _close_group(
        [two_fold_z, three_fold_111, _rotation_about(five_fold_axis, 72.0)],
        order=60,
    )


def _icosahedral_i1_matrices() -> torch.Tensor:
    """I1: the 222 setting with a 5-fold axis at ``(0, 1, PHI)``, i.e. 31.7 degrees from z."""
    return _icosahedral_222((0.0, 1.0, PHI))


def _icosahedral_i2_matrices() -> torch.Tensor:
    """I2: the 222 setting with a 5-fold axis at ``(0, PHI, 1)``, i.e. 31.7 degrees from y."""
    return _icosahedral_222((0.0, PHI, 1.0))


def _icosahedral_i_matrices() -> torch.Tensor:
    """I: an alias of I2."""
    return _icosahedral_i2_matrices()
