[project]
name = "cryosim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "biopython>=1.85",
    "biotite>=1.4.0",
    "cryosparc-tools>=4.7.1",
    "h5py>=3.14.0",
    "lightning>=2.5.5",
    "matplotlib>=3.10.6",
    "mrcfile>=1.5.4",
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "requests>=2.32.5",
    "scikit-image>=0.25.2",
    "scipy>=1.16.2",
    "starfile>=0.5.13",
    "torch>=2.8.0",
    "torchinterp1d>=1.1",
    "tqdm>=4.67.1",
]
