"""
Effective coherent damage applied to the specimen's potential.

The published protein signal-decay law is extended isotropically to the
three-dimensional Fourier radius. This is a model of the coherent average
potential, not a microscopic chemical-damage trajectory. It does not specify
the diffuse scattering generated by damaged structures. Solvent evolution
must be modeled separately; stationary solvent power does not imply that its
configurations remain correlated throughout an exposure.

So the particle generators damage the specimen's 3D potential before the
solvent is added: a radial envelope in 3D Fourier space, which by the
projection-slice theorem is exactly the 2D envelope on the projected
specimen in the linear projection approximation and leaves the subsequently
added ice untouched by the protein envelope. This equivalence is not exact
for nonlinear multislice propagation.

**Which envelope.** A movie is a sum of frames, each imaging a specimen at a
different accumulated dose, recombined by motion correction under per-frequency
weights. The signal that survives is therefore the weight-average of the
frames' own damage states,

.. math::  E(k) = \\frac{\\sum_i w_i(k)\\, q_i(k)}{\\sum_i w_i(k)},
           \\qquad q_i = e^{-N_i / 2 N_e(k)},

with :math:`N_i` the dose accumulated by frame *i*. :func:`frame_damage_envelope`
evaluates this using frame-midpoint dose samples and the run's measured
weights. It approximates the frame-resolved render when imaging is linear in
the potential; applying it before multislice is an additional effective-volume
approximation. Processing weights are not intrinsic material properties.

The closed forms in :func:`specter.aberrations.dose_envelope` are the two
limits of that sum: ``weighted=False`` is uniform weights, and ``weighted=True``
is the Grant & Grigorieff optimal filter :math:`w_i \\propto q_i` *with the
frame sum renormalised to fixed noise*. The second is not a property of a
specimen -- it folds in how the frames were combined and what that did to the
noise -- so it does not belong on a potential when the detector is separately
applying the run's real weights and the real noise gain they cause. Prefer
:func:`frame_damage_envelope` on any path that fractionates the exposure.
"""

from __future__ import annotations

from collections.abc import Sequence

import torch

from ..aberrations._envelopes import critical_exposure, dose_envelope
from ..fft import apply_radial_envelope_


def frame_damage_envelope(
    k: torch.Tensor,
    dose: float,
    n_frames: int,
    *,
    weights: torch.Tensor | None = None,
    weights_max_frequency: float | None = None,
    pre_exposure: float = 0.0,
    voltage: float | None = None,
    frames: Sequence[int] | None = None,
) -> torch.Tensor:
    """
    Weight-averaged damage envelope of an explicit frame sum.

    Parameters
    ----------
    k : torch.Tensor
        Frequency magnitude grid, in 1/Angstrom.
    dose : float
        Exposure accumulated across the whole movie, in e-/A^2.
    n_frames : int
        Number of frames the exposure is divided into.
    weights : torch.Tensor or None, optional
        Motion correction's per-frame, per-frequency weights, shape
        ``(n_frames, n_bins)`` over a radial axis. None means a plain sum
        (every weight 1), which reduces to the unweighted closed form.
    weights_max_frequency : float or None, optional
        Frequency of the weights' last radial bin, in 1/Angstrom. Required
        when ``weights`` is given, since the axis is the movie's Nyquist and
        not in general the image's.
    pre_exposure : float, optional
        Dose already received when the movie started. Default 0.
    voltage : float or None, optional
        Accelerating voltage in kV; None means 300.
    frames : sequence of int or None, optional
        Restrict the average to these frame indices, the exposure itself
        still running over all ``n_frames``. This is the envelope of one
        group of frames within the movie, which is what a frame-resolved
        render damages each of its states by. None (default) averages over
        the whole movie.

    Returns
    -------
    torch.Tensor
        Amplitude envelope in (0, 1], the shape of ``k``.
    """
    if n_frames < 1:
        raise ValueError("n_frames must be at least 1")
    if weights is not None:
        if weights.shape[0] != n_frames:
            raise ValueError(
                f"weights carry {weights.shape[0]} frames but n_frames={n_frames}"
            )
        if weights_max_frequency is None:
            raise ValueError("weights_max_frequency is required alongside weights")
    ne = critical_exposure(k, voltage=voltage)
    per_frame = dose / n_frames
    num = torch.zeros_like(k)
    den = torch.zeros_like(k)
    idx = None
    if weights is not None:
        n_bins = weights.shape[1]
        r = k / weights_max_frequency
        idx = torch.clamp((r * (n_bins - 1)).round().long(), 0, n_bins - 1)
    for i in range(n_frames) if frames is None else frames:
        # Midpoint of the frame's own dose interval: the frame integrates over
        # it, and to first order that is its centre.
        n_i = pre_exposure + (i + 0.5) * per_frame
        q = torch.exp(-n_i / (2.0 * ne))
        if idx is None or weights is None:
            num += q
            den += 1.0
        else:
            w = weights[i].to(k.device)[idx]
            num += w * q
            den += w
        del q
    env = num / den.clamp(min=1e-12)
    # k == 0 has ne == inf and q == 1 exactly; guard against 0/0 from a
    # frequency where every weight is zero.
    return torch.where(torch.isfinite(env), env, torch.ones_like(env))


def apply_dose_damage(
    V: torch.Tensor,
    pixel_size: float,
    dose: torch.Tensor | float,
    pre_exposure: torch.Tensor | float = 0.0,
    weighted: bool = True,
    voltage: float | None = None,
    n_frames: int | None = None,
    frame_weights: torch.Tensor | None = None,
    frame_weights_max_frequency: float | None = None,
) -> torch.Tensor:
    """
    Attenuate a potential volume by the dose envelope, in place per item.

    Parameters
    ----------
    V : torch.Tensor
        Real potential of shape ``(B, Z, Y, X)`` (or ``(Z, Y, X)``). Every
        item is overwritten with its damaged form; the mean (``k = 0``) is
        preserved exactly, so the total scattering mass is unchanged.
    pixel_size : float
        Voxel size in Angstrom, isotropic.
    dose : torch.Tensor or float
        Exposure accumulated in the image, in e-/A^2, one value per batch
        item or a scalar.
    pre_exposure : torch.Tensor or float, optional
        Exposure already received when the image started, per item or
        scalar. Default 0.
    weighted : bool, optional
        Which closed form to use when ``n_frames`` is None. See
        :func:`specter.aberrations.dose_envelope`.
    voltage : float or None, optional
        Accelerating voltage in kV, rescaling the critical exposure; None
        means 300 kV.
    n_frames : int or None, optional
        When given, the envelope is the explicit frame sum
        (:func:`frame_damage_envelope`) rather than a closed form, and
        ``weighted`` is ignored. This is the accurate form for a movie.
    frame_weights : torch.Tensor or None, optional
        Motion correction's ``(n_frames, n_bins)`` weights, used with
        ``n_frames``. None means a plain sum.
    frame_weights_max_frequency : float or None, optional
        Frequency of the weights' last bin, in 1/Angstrom.

    Returns
    -------
    torch.Tensor
        ``V`` itself, damaged.
    """
    squeeze = V.ndim == 3
    if squeeze:
        V = V.unsqueeze(0)
    dose_t = torch.as_tensor(dose, dtype=torch.float32).reshape(-1)
    pre_t = torch.as_tensor(pre_exposure, dtype=torch.float32).reshape(-1)
    for i in range(V.shape[0]):
        d = float(dose_t[i if dose_t.numel() > 1 else 0])
        p = float(pre_t[i if pre_t.numel() > 1 else 0])
        if d == 0.0 and p == 0.0:
            continue

        def envelope(k: torch.Tensor, d: float = d, p: float = p) -> torch.Tensor:
            if n_frames is None:
                return dose_envelope(
                    k,
                    torch.tensor(d, device=k.device),
                    pre_exposure=p,
                    weighted=weighted,
                    voltage=voltage,
                )
            return frame_damage_envelope(
                k,
                d,
                n_frames,
                weights=frame_weights,
                weights_max_frequency=frame_weights_max_frequency,
                pre_exposure=p,
                voltage=voltage,
            )

        try:
            apply_radial_envelope_(V[i], pixel_size, envelope)
        except torch.OutOfMemoryError:
            if not V.is_cuda:
                raise
            # A canvas the device can hold once but not twice (thick ice in
            # a large box): the transform runs on the host instead. Slow,
            # but the same numbers.
            torch.cuda.empty_cache()
            host = V[i].cpu()
            apply_radial_envelope_(host, pixel_size, envelope)
            V[i].copy_(host)
            del host
    return V.squeeze(0) if squeeze else V
