"""
Filament orientation: aligning each monomer's stacking axis to the local
path tangent, plus an accumulated helical twist -- the same screw-symmetry
construction (translate along the filament axis, rotate about it) real
helical polymers like F-actin and microtubule protofilaments use.

This module only computes the path-tangent rotations; identifying which
axis of the monomer itself is the "stacking axis" is a separate, earlier
step (see ``TomogramSpecimenGenerator._stamp_filaments``, which pre-rotates
each monomer's own coordinates via
``specter.specimen.membrane._placement.align_principal_axis_to_z`` before
building its potential template -- the same argument that function's
docstring makes for membrane proteins' extramembrane domains applies here: a
fetched PDB's native coordinate axes have no relationship to its real
stacking direction). Using a monomer's longest principal axis as its
stacking axis is an approximation (a true protofilament/actin docking axis
comes from the real inter-subunit contact geometry, not a monomer's own
inertia tensor), at the same level of fidelity CTS's own WIP filament code
aimed for -- not a validated structural docking.
"""

from __future__ import annotations

import math

import roma
import torch


def filament_tangents(positions_xyz: torch.Tensor) -> torch.Tensor:
    """
    Per-monomer unit tangent along a filament path.

    Parameters
    ----------
    positions_xyz : torch.Tensor
        Monomer-center positions, shape ``(n, 3)``, physical ``(x, y, z)``.

    Returns
    -------
    torch.Tensor
        Unit tangents, shape ``(n, 3)``. Tangent ``i`` points from monomer
        ``i`` towards monomer ``i + 1`` for all but the last monomer, which
        reuses the second-to-last tangent (no outgoing segment exists at the
        end of the path). A single-monomer path gets an arbitrary tangent
        of ``(0, 0, 1)``.
    """
    n = positions_xyz.shape[0]
    if n == 1:
        return torch.tensor([[0.0, 0.0, 1.0]])
    diffs = positions_xyz[1:] - positions_xyz[:-1]
    tangents = diffs / diffs.norm(dim=-1, keepdim=True).clamp_min(1e-8)
    return torch.cat([tangents, tangents[-1:]], dim=0)


def _rotation_aligning(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    """Rotation matrix R such that ``R @ a`` (both normalized) equals ``b``.

    Same small "align two vectors" construction as
    ``membrane._placement._rotation_aligning`` -- kept as a local copy
    rather than a cross-module import, matching this codebase's established
    per-generator zero-cross-coupling convention.
    """
    a = a / a.norm().clamp_min(1e-8)
    b = b / b.norm().clamp_min(1e-8)

    cos_angle = torch.clamp((a * b).sum(), -1.0, 1.0)
    axis = torch.linalg.cross(a, b)
    axis_norm = axis.norm()

    if float(axis_norm) < 1e-6:
        if float(cos_angle) > 0:
            return torch.eye(3)
        perp = torch.linalg.cross(a, torch.tensor([1.0, 0.0, 0.0]))
        if float(perp.norm()) < 1e-6:
            perp = torch.linalg.cross(a, torch.tensor([0.0, 1.0, 0.0]))
        perp = perp / perp.norm()
        return roma.rotvec_to_rotmat((perp * math.pi).unsqueeze(0))[0]

    axis = axis / axis_norm
    angle = torch.arccos(cos_angle)
    return roma.rotvec_to_rotmat((axis * angle).unsqueeze(0))[0]


def filament_orientations(
    positions_xyz: torch.Tensor, twist_deg: float
) -> torch.Tensor:
    """
    Per-monomer rotation matrices: align local +Z to the path tangent, then
    apply an accumulated helical twist about that axis.

    Parameters
    ----------
    positions_xyz : torch.Tensor
        Monomer-center positions, shape ``(n, 3)``, physical ``(x, y, z)``
        (as generated by ``generate_filament_path``).
    twist_deg : float
        Helical twist per monomer, degrees, accumulated along the filament
        (monomer ``i``'s spin is ``i * twist_deg``). 0 for a filament with
        no twist along a single strand (e.g. a microtubule protofilament);
        nonzero for a genuinely helical polymer (e.g. ~166.15 degrees for
        F-actin).

    Returns
    -------
    torch.Tensor
        Rotation matrices, shape ``(n, 3, 3)``, physical ``(x, y, z)``
        convention (matching ``rotate_volume``'s affine matrices), such
        that each ``R[i] @ [0, 0, 1]`` equals tangent ``i``.
    """
    tangents = filament_tangents(positions_xyz)
    z_hat = torch.tensor([0.0, 0.0, 1.0])
    twist_rad = math.radians(twist_deg)

    n = positions_xyz.shape[0]
    rotations = torch.empty((n, 3, 3))
    for i in range(n):
        r_align = _rotation_aligning(z_hat, tangents[i])
        r_spin = roma.rotvec_to_rotmat((z_hat * (i * twist_rad)).unsqueeze(0))[0]
        rotations[i] = r_align @ r_spin
    return rotations
