"""
Generate the command reference tables in `docs/api/cli.md`.

Writes `docs-includes/cli-reference.md`, which `docs/api/cli.md` pulls in with
a pymdownx.snippets include. Every flag, type, default and description comes
from the same `click` objects `specter --help` renders, so the page cannot
describe a flag the CLI does not have, or miss one it does.

Usage
-----
    python docs-figures/cli_reference.py

`tests/test_cli_reference_docs.py` fails if the committed file no longer
matches what this script produces, so a CLI change surfaces as a test failure
rather than as silently stale documentation.

Why generate rather than use mkdocs-click
-----------------------------------------
`mkdocs-click` renders a click app straight from a Markdown directive, and its
`:style: table` does work against this CLI -- its default `plain` style does
not, because that one reads help text back out of `ctx.make_formatter()`, and
rich-click writes to a `rich` console instead, so the buffer comes back empty.

Two things it cannot express are the reason for this script:

- **Defaults.** `build_config_options` gives every option a real `default` of
  `None`, so that `ctx.get_parameter_source` can tell "the caller passed this"
  from "the caller left it alone" and unset flags never clobber the TOML. The
  value a field actually falls back to is carried separately, as a string, in
  `show_default`. `mkdocs-click` renders `option.default`, so it would print
  `None` for 297 of this CLI's 299 options -- exactly the column a reader came
  for, uniformly wrong.
- **Panels.** The `_*_GROUPS` lists in `cli/` are the single source of truth
  for `--help`'s panel order, and `configs/*.toml` mirrors that order table for
  table. `mkdocs-click` emits one flat table per command, which drops the
  grouping the rest of the documentation is written against.

Both live on attributes this script reads directly (`show_default`, `panel`).
"""

from __future__ import annotations

import inspect
import re
from collections.abc import Sequence
from pathlib import Path

import click

from specter.cli._cli import cli

#: Commands that are a second name for another command rather than their own.
#: `specter ghostbuster particle` and `specter reconstruct particle` are built
#: by the same `build_reconstruct_group()` call, so documenting both in full
#: would print 38 identical options twice and invite them to drift apart in a
#: reader's mind. The alias gets a pointer instead.
ALIASES: dict[str, str] = {"ghostbuster": "reconstruct"}

#: Panel title used for options that name no panel of their own. Matches the
#: catch-all rich-click falls back to in `--help`.
DEFAULT_PANEL = "Options"

HEADER = "<!-- Generated by docs-figures/cli_reference.py -- do not edit by hand. -->\n"


def anchor(path: tuple[str, ...]) -> str:
    """
    Build the HTML anchor for a command.

    Parameters
    ----------
    path : tuple of str
        Command path, e.g. ``("specter", "build", "tomogram")``.

    Returns
    -------
    str
        Anchor id, e.g. ``specter-build-tomogram``. Derived from the full path
        rather than the leaf name because two different commands share a leaf
        (``reconstruct particle`` and ``ghostbuster particle``), and a leaf-only
        id would silently collide.
    """
    return "-".join(path)


def panel_anchor(path: tuple[str, ...], title: str) -> str:
    """
    Build the HTML anchor for one option panel of a command.

    Parameters
    ----------
    path : tuple of str
        Command path, e.g. ``("specter", "build", "tomogram")``.
    title : str
        Panel title as ``--help`` prints it, e.g. ``"Output & job tracking"``.

    Returns
    -------
    str
        Anchor id, e.g. ``specter-build-tomogram-output-job-tracking``.
        Prefixed with the command because panel titles repeat across commands:
        nine of them are called ``Advanced``.
    """
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return f"{anchor(path)}-{slug}"


def escape_angles(text: str) -> str:
    """
    Escape angle brackets so Markdown does not read them as inline HTML.

    Parameters
    ----------
    text : str
        Help text, which uses angle brackets for placeholders
        (``<output_dir>/[<project>/]particles/J00N/``).

    Returns
    -------
    str
        The same text with ``<`` and ``>`` written as entities. Without this,
        Python-Markdown treats ``<artifact>`` as an unknown HTML tag and drops
        it from the rendered page, silently deleting the placeholder the
        sentence is about.
    """
    return text.replace("<", "&lt;").replace(">", "&gt;")


def cell(text: str | None) -> str:
    """
    Flatten help text into something safe inside a Markdown table cell.

    Parameters
    ----------
    text : str or None
        Raw help text, possibly spanning several lines.

    Returns
    -------
    str
        Single-line text with pipes and angle brackets escaped, or an empty
        string. Table cells cannot contain newlines, so a multi-line help
        string is collapsed onto one line.
    """
    if not text:
        return ""
    flat = re.sub(r"\s+", " ", text).strip()
    return escape_angles(flat).replace("|", r"\|")


def alternatives(values: Sequence[str]) -> str:
    """
    Render a set of accepted values separated by pipes.

    Parameters
    ----------
    values : sequence of str
        The accepted values, e.g. ``["multislice", "rytov"]``.

    Returns
    -------
    str
        Each value as its own code span, joined by an escaped pipe. The
        separator has to sit outside the code spans: inside one, Markdown
        escapes do not apply, so a ``\\|`` written there survives into the page
        as a visible backslash.
    """
    return " \\| ".join(f"`{v}`" for v in values)


def type_repr(param: click.Parameter) -> str:
    """
    Render a parameter's accepted values the way ``--help`` shows them.

    Parameters
    ----------
    param : click.Parameter
        The option or argument to describe.

    Returns
    -------
    str
        A Markdown fragment: the choices for a ``click.Choice``, the explicit
        metavar where one is set (``True\\|False`` for the boolean fields), and
        otherwise Click's own type name in caps (``TEXT``, ``INTEGER``,
        ``FLOAT``).
    """
    if isinstance(param.type, click.Choice):
        return alternatives(param.type.choices)
    if param.metavar:
        return alternatives(param.metavar.split("|"))
    if isinstance(param, click.Option) and param.is_flag:
        return "flag"
    return f"`{param.type.name.upper()}`"


def default_repr(option: click.Option) -> str:
    """
    Render an option's fallback value.

    Parameters
    ----------
    option : click.Option
        The option to describe.

    Returns
    -------
    str
        The value the field falls back to when the flag is not passed. Read
        from ``show_default`` rather than ``default``: a config-driven option's
        real ``default`` is always ``None`` so that an unpassed flag can be
        told apart from one passed explicitly, and the true fallback is carried
        as a display string alongside it. Options built by hand (``--yes`` on
        ``specter cache clean``) carry no such string and fall back to their
        real ``default``. An option with neither is a required input the run is
        about, and says so.

        A field whose fallback genuinely is nothing renders as ``_none_``
        rather than as the string ``"None"`` ``--help`` prints, so that it
        cannot be misread as a literal value to pass.
    """
    shown = option.show_default
    if isinstance(shown, str) and shown != "None":
        return f"`{shown}`"
    if not isinstance(shown, str) and option.default is not None:
        return f"`{option.default}`"
    if option.required:
        return "_required_"
    return "_none_"


def panels_of(cmd: click.Command) -> list[tuple[str, list[click.Option]]]:
    """
    Group a command's options into ``--help``'s panels, in emission order.

    Parameters
    ----------
    cmd : click.Command
        The command whose options to group.

    Returns
    -------
    list of (str, list of click.Option)
        ``(panel title, options)``. Order follows the command's parameter list,
        which is what rich-click itself renders from, so the panels come out in
        the same order as ``--help`` and as the matching ``configs/*.toml``.
        ``--help`` itself is dropped: it is on every command and says the same
        thing each time.
    """
    grouped: dict[str, list[click.Option]] = {}
    for param in cmd.params:
        if not isinstance(param, click.Option) or param.name == "help":
            continue
        grouped.setdefault(getattr(param, "panel", None) or DEFAULT_PANEL, []).append(
            param
        )
    return list(grouped.items())


def usage(path: tuple[str, ...], cmd: click.Command) -> str:
    """
    Build the usage line for a command.

    Parameters
    ----------
    path : tuple of str
        Command path, e.g. ``("specter", "jobs", "show")``.
    cmd : click.Command
        The command itself.

    Returns
    -------
    str
        The usage string, e.g. ``specter jobs show [OPTIONS] JOB_ID``.
    """
    ctx = click.Context(cmd, info_name=" ".join(path))
    return " ".join([" ".join(path), *cmd.collect_usage_pieces(ctx)])


def walk(
    cmd: click.Command, path: tuple[str, ...]
) -> list[tuple[tuple[str, ...], click.Command]]:
    """
    Collect a command and its subcommands, depth-first, in registration order.

    Parameters
    ----------
    cmd : click.Command
        Root command to walk.
    path : tuple of str
        Path of ``cmd`` itself.

    Returns
    -------
    list of (tuple of str, click.Command)
        Every command reachable from ``cmd``, including ``cmd``. Subcommands
        keep the order they were added in, so the reference lists them in the
        order the CLI itself does rather than alphabetically.
    """
    found = [(path, cmd)]
    if isinstance(cmd, click.Group):
        for name, sub in cmd.commands.items():
            found.extend(walk(sub, path + (name,)))
    return found


def render_command(path: tuple[str, ...], cmd: click.Command, level: int) -> list[str]:
    """
    Render one command's section.

    Parameters
    ----------
    path : tuple of str
        Command path, e.g. ``("specter", "build", "tomogram")``.
    cmd : click.Command
        The command to render.
    level : int
        Markdown heading level for the section.

    Returns
    -------
    list of str
        Markdown lines: heading, description, usage block, a subcommand table
        for a group, and one table per option panel for a leaf command.
    """
    out = [
        f"{'#' * level} `{' '.join(path)}` {{ #{anchor(path)} }}",
        "",
    ]

    if cmd.help:
        out += [escape_angles(inspect.cleandoc(cmd.help)), ""]

    out += ["```text", usage(path, cmd), "```", ""]

    if isinstance(cmd, click.Group):
        out += ["| Command | Description |", "| --- | --- |"]
        for name, sub in cmd.commands.items():
            link = f"[`{name}`](#{anchor(path + (name,))})"
            out.append(f"| {link} | {cell(sub.get_short_help_str(limit=200))} |")
        out.append("")

    args = [p for p in cmd.params if isinstance(p, click.Argument)]
    if args:
        out += [
            "**Arguments**",
            "",
            "| Argument | Type | Required |",
            "| --- | --- | --- |",
        ]
        for arg in args:
            required = "yes" if arg.required else "no"
            out.append(f"| `{arg.name.upper()}` | {type_repr(arg)} | {required} |")
        out.append("")

    for title, options in panels_of(cmd):
        # An inline attr_list id rather than a heading: the panels need to be
        # linkable from the user guide ("lives under Advanced"), but there are
        # ~90 of them, and as headings they would bury the command list in the
        # sidebar. Only headings enter the table of contents.
        out += [
            f"**{title}**{{ #{panel_anchor(path, title)} }}",
            "",
            "| Flag | Type | Default | Description |",
            "| --- | --- | --- | --- |",
        ]
        for option in options:
            flags = ", ".join(f"`{o}`" for o in option.opts)
            out.append(
                f"| {flags} | {type_repr(option)} | {default_repr(option)} "
                f"| {cell(option.help)} |"
            )
        out.append("")

    return out


def render() -> str:
    """
    Render the whole command reference.

    Returns
    -------
    str
        The full Markdown fragment written to ``docs-includes/cli-reference.md``.
    """
    out = [HEADER]

    for path, cmd in walk(cli, ("specter",)):
        # Skip the root: `docs/api/cli.md`'s own prose introduces the CLI, and
        # a second top-level section repeating it would only add a heading.
        if len(path) == 1:
            continue

        target = ALIASES.get(path[1])
        if target is not None:
            if len(path) > 2:
                continue
            alias_path = (path[0], target)
            out += [
                f"## `{' '.join(path)}` {{ #{anchor(path)} }}",
                "",
                f"A second name for [`{' '.join(alias_path)}`]"
                f"(#{anchor(alias_path)}), with the same subcommands and flags. "
                "The solver is called Ghostbuster throughout the Python API and "
                "the user guide, so it answers to that name here too.",
                "",
            ]
            continue

        out += render_command(path, cmd, level=len(path))

    return "\n".join(out).rstrip() + "\n"


def main() -> None:
    """Write the rendered reference to ``docs-includes/cli-reference.md``."""
    dest = Path(__file__).resolve().parent.parent / "docs-includes" / "cli-reference.md"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(render())
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
